making NAME and WORKAREA as optional in the .project_props file. Current dir name as the defaults for them.

diff --git a/stc b/stc
--- a/stc
+++ b/stc
@@ -88,7 +88,7 @@ if [ -r $PROJ_PROPS ]; then
 			NAME=$value
 			;;
 		    "WORKAREA")
-			eval "WORKAREA=$value"
+			eval "W_PATH=$value"
 			;;
 		    "CDDIR")
 			eval "CDDIR=$value"
@@ -119,7 +119,7 @@ fi
 ##
 ## Were all required parameters provided
 ##
-for par in NAME WORKAREA IMAGE; do
+for par in IMAGE; do
 	eval parval=\$$par
 	if [ -z "$parval" ]; then
 		echo "ERROR: $PROJ_PROPS does not provide value for $par." 1>&2
@@ -130,8 +130,9 @@ done
 ##
 ## Does the provided WORKAREA path exist?
 ##
-if [ ! -d "$WORKAREA" ]; then
-	echo "ERROR: WORKAREA directory $WORKAREA does not exist. Exiting..." 1>&2
+W_PATH=${W_PATH:-"."}
+if [ ! -d "$W_PATH" ]; then
+	echo "ERROR: WORKAREA directory $W_PATH does not exist. Exiting..." 1>&2
 	failed=1
 fi
 
@@ -142,7 +143,8 @@ if [ "$failed" -eq 1 ]; then
 	exit 1
 fi
 
-WORKAREA=$(cd $WORKAREA; pwd)
+WORKAREA=$(cd $W_PATH; pwd)
+NAME=${NAME:-$(basename $WORKAREA)}
 MOUNTPOINT=/hostFS/`basename $WORKAREA`
 CDDIR=${CDDIR:-$MOUNTPOINT}
 launch_command=${launch_command:-$COMMAND}
